apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: <function_name>
spec:
  template:
    spec:
      containers:
        - image: docker.io/<registry>/<function_name>:<version>
          ports:
            - containerPort: 8080